import { PERMISSIONS } from "../constants/permissions.js";

export const DEFAULT_PERMISSIONS = {
  SUPER_ADMIN: Object.values(PERMISSIONS),

  ADMIN: [
    PERMISSIONS.DASHBOARD_VIEW,

    PERMISSIONS.PROFILE_VIEW,
    PERMISSIONS.PROFILE_UPDATE,

    PERMISSIONS.HIGHLIGHT_CREATE,
    PERMISSIONS.HIGHLIGHT_READ,
    PERMISSIONS.HIGHLIGHT_UPDATE,
    PERMISSIONS.HIGHLIGHT_DELETE,

    PERMISSIONS.HERO_CREATE,
    PERMISSIONS.HERO_READ,
    PERMISSIONS.HERO_UPDATE,
    PERMISSIONS.HERO_DELETE,

    PERMISSIONS.PROGRAM_CREATE,
    PERMISSIONS.PROGRAM_READ,
    PERMISSIONS.PROGRAM_UPDATE,
    PERMISSIONS.PROGRAM_DELETE,

    PERMISSIONS.EVENT_CREATE,
    PERMISSIONS.EVENT_READ,
    PERMISSIONS.EVENT_UPDATE,
    PERMISSIONS.EVENT_DELETE,

    PERMISSIONS.NEWS_CREATE,
    PERMISSIONS.NEWS_READ,
    PERMISSIONS.NEWS_UPDATE,
    PERMISSIONS.NEWS_DELETE,

    PERMISSIONS.NOTICE_CREATE,
    PERMISSIONS.NOTICE_READ,
    PERMISSIONS.NOTICE_UPDATE,
    PERMISSIONS.NOTICE_DELETE,

    PERMISSIONS.DOWNLOAD_CREATE,
    PERMISSIONS.DOWNLOAD_READ,
    PERMISSIONS.DOWNLOAD_UPDATE,
    PERMISSIONS.DOWNLOAD_DELETE,

    PERMISSIONS.GALLERY_CREATE,
    PERMISSIONS.GALLERY_READ,
    PERMISSIONS.GALLERY_UPDATE,
    PERMISSIONS.GALLERY_DELETE,

    PERMISSIONS.CONTACT_READ,
    PERMISSIONS.CONTACT_UPDATE,

    PERMISSIONS.ABOUT_READ,
    PERMISSIONS.ABOUT_UPDATE,

    PERMISSIONS.ADMISSION_READ,
    PERMISSIONS.ADMISSION_UPDATE,

    PERMISSIONS.CAMPUS_CHIEF_READ,
    PERMISSIONS.CAMPUS_CHIEF_UPDATE,
  ],

  STAFF: [
    PERMISSIONS.DASHBOARD_VIEW,

    PERMISSIONS.PROFILE_VIEW,
    PERMISSIONS.PROFILE_UPDATE,

    PERMISSIONS.NEWS_READ,
    PERMISSIONS.NEWS_CREATE,
    PERMISSIONS.NEWS_UPDATE,

    PERMISSIONS.NOTICE_READ,
    PERMISSIONS.NOTICE_CREATE,
    PERMISSIONS.NOTICE_UPDATE,

    PERMISSIONS.GALLERY_READ,
    PERMISSIONS.GALLERY_CREATE,
    PERMISSIONS.GALLERY_UPDATE,
  ],
};
