export const PERMISSIONS = {
  // DASHBOARD
  DASHBOARD_VIEW: "DASHBOARD_VIEW",

  // ADMIN
  ADMIN_CREATE: "ADMIN_CREATE",
  ADMIN_READ: "ADMIN_READ",
  ADMIN_UPDATE: "ADMIN_UPDATE",
  ADMIN_DELETE: "ADMIN_DELETE",

  // NEWS
  NEWS_CREATE: "NEWS_CREATE",
  NEWS_READ: "NEWS_READ",
  NEWS_UPDATE: "NEWS_UPDATE",
  NEWS_DELETE: "NEWS_DELETE",

  // NOTICE
  NOTICE_CREATE: "NOTICE_CREATE",
  NOTICE_READ: "NOTICE_READ",
  NOTICE_UPDATE: "NOTICE_UPDATE",
  NOTICE_DELETE: "NOTICE_DELETE",

  // GALLERY
  GALLERY_CREATE: "GALLERY_CREATE",
  GALLERY_READ: "GALLERY_READ",
  GALLERY_UPDATE: "GALLERY_UPDATE",
  GALLERY_DELETE: "GALLERY_DELETE",

  // HERO
  HERO_CREATE: "HERO_CREATE",
  HERO_READ: "HERO_READ",
  HERO_UPDATE: "HERO_UPDATE",
  HERO_DELETE: "HERO_DELETE",

  // PROGRAM
  PROGRAM_CREATE: "PROGRAM_CREATE",
  PROGRAM_READ: "PROGRAM_READ",
  PROGRAM_UPDATE: "PROGRAM_UPDATE",
  PROGRAM_DELETE: "PROGRAM_DELETE",

  // EVENT
  EVENT_CREATE: "EVENT_CREATE",
  EVENT_READ: "EVENT_READ",
  EVENT_UPDATE: "EVENT_UPDATE",
  EVENT_DELETE: "EVENT_DELETE",

  // DOWNLOAD
  DOWNLOAD_CREATE: "DOWNLOAD_CREATE",
  DOWNLOAD_READ: "DOWNLOAD_READ",
  DOWNLOAD_UPDATE: "DOWNLOAD_UPDATE",
  DOWNLOAD_DELETE: "DOWNLOAD_DELETE",

  // ABOUT
  ABOUT_READ: "ABOUT_READ",
  ABOUT_UPDATE: "ABOUT_UPDATE",

  // CONTACT
  CONTACT_READ: "CONTACT_READ",
  CONTACT_UPDATE: "CONTACT_UPDATE",

  // ADMISSION
  ADMISSION_READ: "ADMISSION_READ",
  ADMISSION_UPDATE: "ADMISSION_UPDATE",

  // CAMPUS CHIEF
  CAMPUS_CHIEF_READ: "CAMPUS_CHIEF_READ",
  CAMPUS_CHIEF_UPDATE: "CAMPUS_CHIEF_UPDATE",

  // PROFILE
  PROFILE_VIEW: "PROFILE_VIEW",
  PROFILE_UPDATE: "PROFILE_UPDATE",

  // ROLE
  ROLE_CREATE: "ROLE_CREATE",
  ROLE_READ: "ROLE_READ",
  ROLE_UPDATE: "ROLE_UPDATE",
  ROLE_DELETE: "ROLE_DELETE",
};
